package com.github.panlelapin.simplercal

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp

internal const val PREFERENCES_NAME = "simplercal"
internal const val SELECTED_CALENDAR_KEY = "selected_calendar_id"
internal const val DAY_ACCENT_COLOR_KEY = "day_accent_color"
internal const val THEME_MODE_KEY = "theme_mode"
internal const val SCROLL_MODE_KEY = "scroll_mode"
internal const val DEBUG1_OUTLINE_COLOR_KEY = "debug1_outline_color"
internal const val SIMULATION_MODE_KEY = "simulation_mode"
internal const val GITHUB_URL = "https://github.com/panlelapin/simplercal"
internal const val WEEK_DAY_COUNT = 7
internal const val WEEKEND_START_INDEX = 5
internal const val COMPACT_DAY_WEIGHT = 6.5f
internal const val TOTAL_DAY_WEIGHT = 100f
internal const val DAY_STATE_ANIMATION_DURATION_MILLIS = 500
internal const val NANOS_PER_MILLISECOND = 1_000_000L
internal const val DAY_CONTENT_TEXT = "dolor sit amet bla bla truc bigoudi plan plan proutcul"
internal const val EXPANDED_CONTENT_LINE_COUNT = 9
internal const val COMPACT_CONTENT_LINE_COUNT = 1
internal val DAY_LABEL_HORIZONTAL_PADDING = 8.dp
internal val DAY_SEPARATOR_THICKNESS = 1.5.dp
internal val DAY_SUBCONTAINER_CORNER_RADIUS = 10.dp
internal val DAY_ACCENT_STRIPE_WIDTH = 3.dp
internal val MINIMUM_RIGHT_GESTURE_GUTTER = 24.dp
internal const val RIGHT_GESTURE_GUTTER_FRACTION = 0.225f
internal const val BOTTOM_GESTURE_GUTTER_FRACTION = 0.72f
internal const val MIN_FRACTION = 0f
internal const val MAX_FRACTION = 1f
internal const val CONTRAST_OFFSET = 0.05f
internal const val COLOR_ALPHA = 1f
internal const val OUTLINE_BLEND_FRACTION = 0.35f
internal const val DISCRETE_ACTIVATION_OFFSET = 0.5f
internal const val ARGB_GOOGLE_VIOLET = 0xFF6750A4L
internal const val ARGB_SAMSUNG_BLUE = 0xFF0381FEL
internal const val ARGB_INDIGO = 0xFF3F51B5L
internal const val ARGB_TEAL = 0xFF006B5FL
internal const val ARGB_MATERIAL_VIOLET = 0xFF6750A4L
internal const val ARGB_PLUM = 0xFF7D3C98L
internal const val ARGB_RASPBERRY = 0xFFA7355CL
internal const val ARGB_EMERALD_GREEN = 0xFF2E7D32L
internal const val ARGB_MATERIAL_RED = 0xFFF44336L
internal const val ARGB_MATERIAL_RED_A100 = 0xFFFF8A80L
internal const val ARGB_MATERIAL_RED_A200 = 0xFFFF5252L
internal const val ARGB_MATERIAL_RED_A400 = 0xFFFF1744L
internal const val ARGB_MATERIAL_RED_A700 = 0xFFD50000L
internal const val ARGB_PINK = 0xFFE91E63L
internal const val ARGB_MATERIAL_PINK_A100 = 0xFFFF80ABL
internal const val ARGB_MATERIAL_PINK_A200 = 0xFFFF4081L
internal const val ARGB_MATERIAL_PINK_A400 = 0xFFF50057L
internal const val ARGB_MATERIAL_PINK_A700 = 0xFFC51162L
internal const val ARGB_MATERIAL_PURPLE = 0xFF9C27B0L
internal const val ARGB_MATERIAL_PURPLE_A100 = 0xFFEA80FCL
internal const val ARGB_MATERIAL_PURPLE_A200 = 0xFFE040FBL
internal const val ARGB_MATERIAL_PURPLE_A400 = 0xFFD500F9L
internal const val ARGB_MATERIAL_PURPLE_A700 = 0xFFAA00FFL
internal const val ARGB_MATERIAL_DEEP_PURPLE = 0xFF673AB7L
internal const val ARGB_MATERIAL_DEEP_PURPLE_A100 = 0xFFB388FFL
internal const val ARGB_MATERIAL_DEEP_PURPLE_A200 = 0xFF7C4DFFL
internal const val ARGB_MATERIAL_DEEP_PURPLE_A400 = 0xFF651FFFL
internal const val ARGB_MATERIAL_DEEP_PURPLE_A700 = 0xFF6200EAL
internal const val ARGB_MATERIAL_INDIGO_A100 = 0xFF8C9EFFL
internal const val ARGB_MATERIAL_INDIGO_A200 = 0xFF536DFEL
internal const val ARGB_MATERIAL_INDIGO_A400 = 0xFF3D5AFEL
internal const val ARGB_MATERIAL_INDIGO_A700 = 0xFF304FFEL
internal const val ARGB_MATERIAL_BLUE = 0xFF2196F3L
internal const val ARGB_MATERIAL_BLUE_A100 = 0xFF82B1FFL
internal const val ARGB_MATERIAL_BLUE_A200 = 0xFF448AFFL
internal const val ARGB_MATERIAL_BLUE_A400 = 0xFF2979FFL
internal const val ARGB_MATERIAL_BLUE_A700 = 0xFF2962FFL
internal const val ARGB_MATERIAL_LIGHT_BLUE = 0xFF03A9F4L
internal const val ARGB_MATERIAL_LIGHT_BLUE_A100 = 0xFF80D8FFL
internal const val ARGB_MATERIAL_LIGHT_BLUE_A200 = 0xFF40C4FFL
internal const val ARGB_MATERIAL_LIGHT_BLUE_A400 = 0xFF00B0FFL
internal const val ARGB_MATERIAL_LIGHT_BLUE_A700 = 0xFF0091EAL
internal const val ARGB_MATERIAL_CYAN = 0xFF00BCD4L
internal const val ARGB_MATERIAL_CYAN_A100 = 0xFF84FFFFL
internal const val ARGB_MATERIAL_CYAN_A200 = 0xFF18FFFFL
internal const val ARGB_MATERIAL_CYAN_A400 = 0xFF00E5FFL
internal const val ARGB_MATERIAL_CYAN_A700 = 0xFF00B8D4L
internal const val ARGB_MATERIAL_TEAL = 0xFF009688L
internal const val ARGB_MATERIAL_TEAL_A100 = 0xFFA7FFEBL
internal const val ARGB_MATERIAL_TEAL_A200 = 0xFF64FFDAL
internal const val ARGB_MATERIAL_TEAL_A400 = 0xFF1DE9B6L
internal const val ARGB_MATERIAL_TEAL_A700 = 0xFF00BFA5L
internal const val ARGB_MATERIAL_GREEN = 0xFF4CAF50L
internal const val ARGB_MATERIAL_GREEN_A100 = 0xFFB9F6CAL
internal const val ARGB_MATERIAL_GREEN_A200 = 0xFF69F0AEL
internal const val ARGB_MATERIAL_GREEN_A400 = 0xFF00E676L
internal const val ARGB_MATERIAL_GREEN_A700 = 0xFF00C853L
internal const val ARGB_MATERIAL_LIGHT_GREEN = 0xFF8BC34AL
internal const val ARGB_MATERIAL_LIGHT_GREEN_A100 = 0xFFCCFF90L
internal const val ARGB_MATERIAL_LIGHT_GREEN_A200 = 0xFFB2FF59L
internal const val ARGB_MATERIAL_LIGHT_GREEN_A400 = 0xFF76FF03L
internal const val ARGB_MATERIAL_LIGHT_GREEN_A700 = 0xFF64DD17L
internal const val ARGB_MATERIAL_LIME = 0xFFCDDC39L
internal const val ARGB_MATERIAL_LIME_A100 = 0xFFF4FF81L
internal const val ARGB_MATERIAL_LIME_A200 = 0xFFEEFF41L
internal const val ARGB_MATERIAL_LIME_A400 = 0xFFC6FF00L
internal const val ARGB_MATERIAL_LIME_A700 = 0xFFAEEA00L
internal const val ARGB_MATERIAL_YELLOW = 0xFFFFEB3BL
internal const val ARGB_MATERIAL_YELLOW_A100 = 0xFFFFFF8DL
internal const val ARGB_MATERIAL_YELLOW_A200 = 0xFFFFFF00L
internal const val ARGB_MATERIAL_YELLOW_A400 = 0xFFFFEA00L
internal const val ARGB_MATERIAL_YELLOW_A700 = 0xFFFFD600L
internal const val ARGB_MATERIAL_AMBER = 0xFFFFC107L
internal const val ARGB_MATERIAL_AMBER_A100 = 0xFFFFE57FL
internal const val ARGB_MATERIAL_AMBER_A200 = 0xFFFFD740L
internal const val ARGB_MATERIAL_AMBER_A400 = 0xFFFFC400L
internal const val ARGB_MATERIAL_AMBER_A700 = 0xFFFFAB00L
internal const val ARGB_MATERIAL_ORANGE = 0xFFFF9800L
internal const val ARGB_MATERIAL_ORANGE_A100 = 0xFFFFD180L
internal const val ARGB_MATERIAL_ORANGE_A200 = 0xFFFFAB40L
internal const val ARGB_MATERIAL_ORANGE_A400 = 0xFFFF9100L
internal const val ARGB_MATERIAL_ORANGE_A700 = 0xFFFF6D00L
internal const val ARGB_MATERIAL_DEEP_ORANGE = 0xFFFF5722L
internal const val ARGB_MATERIAL_DEEP_ORANGE_A100 = 0xFFFF9E80L
internal const val ARGB_MATERIAL_DEEP_ORANGE_A200 = 0xFFFF6E40L
internal const val ARGB_MATERIAL_DEEP_ORANGE_A400 = 0xFFFF3D00L
internal const val ARGB_MATERIAL_DEEP_ORANGE_A700 = 0xFFDD2C00L
internal const val ARGB_MATERIAL_BROWN = 0xFF795548L
internal const val ARGB_MATERIAL_GREY = 0xFF9E9E9EL
internal const val ARGB_MATERIAL_BLUE_GREY = 0xFF607D8BL
internal val DAY_SUBCONTAINER_SHAPE = RoundedCornerShape(DAY_SUBCONTAINER_CORNER_RADIUS)
internal val DAY_ABBREVIATIONS = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
