config:
  validation: true
  warningsAsErrors: true
  excludes: []

comments:
  active: true
complexity:
  active: true
coroutines:
  active: true
empty-blocks:
  active: true
exceptions:
  active: true
naming:
  active: true
  FunctionNaming:
    ignoreAnnotated: [Composable]
performance:
  active: true
potential-bugs:
  active: true
style:
  active: true
